name: Deploy Azure Static Web Apps application
description: Deploy Azure Static Web Apps application
author: Antoine Milochau
inputs:
  projectWorkspace:
    description: The path to the project to build
    required: true
  projectOutput:
    description: The path to the output of the build project
    required: true
  staticWebAppsId:
    description: The ID of the Azure Static Web Apps
    required: true 
  githubToken:
    description: The GitHub token, typically get from secrets.GITHUB_TOKEN
    required: true
runs:
  using: composite
  steps:
    - name: Determine Static Web Apps deployment token
      id: get-token
      shell: bash
      run: |
        secrets=$(az rest --method post --url '${{ inputs.staticWebAppsId }}/listsecrets?api-version=2020-06-01')
        deploymentToken=$(fromJson(secrets).properties.apiKey)
        echo "::set-output name=deploymentToken::$deploymentToken"  
    - name: Build and deploy Azure Static Web Apps application 
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ steps.get-token.outputs.deploymentToken }}
        repo_token: ${{ inputs.githubToken }}
        action: 'upload'
        app_location: ${{ inputs.projectWorkspace }}
        output_location: ${{ inputs.outputWorkspace }}
