name: Deploy Azure Static Web Apps application
description: Deploy Azure Static Web Apps application
author: Antoine Milochau
inputs:
  projectWorkspace:
    description: The path to the project to build
    required: true
  projectOutput:
    description: The path to the output of the build project
    required: true
  azureStaticWebAppsApiToken:
    description: The token from the Azure Static Web Apps; could be found from the Azure Portal
    required: true 
  githubToken:
    description: The GitHub token, typically get from secrets.GITHUB_TOKEN
    required: true
  nodeVersion:
    description: The Node.js version to use
    default: 16.x
runs:
  using: composite
  steps:
    - name: Build and deploy Azure Static Web Apps application 
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ inputs.azureStaticWebAppsApiToken }}
        repo_token: ${{ inputs.githubToken }}
        action: 'upload'
        app_location: ${{ inputs.projectWorkspace }}
        output_location: ${{ inputs.outputWorkspace }}
