name: Deploy Azure Static Web Apps application
description: Deploy Azure Static Web Apps application
author: Antoine Milochau
inputs:
  azureCredentials:
    description: Azure credentials, typically get from secrets.AZURE_CREDENTIALS
    required: true
  applicationName:
    description: The application name, as defined on Azure
    required: true 
  projectWorkspace:
    description: The path to the project to build
    required: true
  projectOutput:
    description: The path to the output of the build project
    required: true
  githubToken:
    description: The GitHub token, typically get from secrets.GITHUB_TOKEN
    required: true
runs:
  using: composite
  steps:
    - name: Login on Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azureCredentials }}
    - name: Determine Static Web Apps deployment token
      id: get-secrets
      shell: bash
      run: |
        secrets=$(az staticwebapp secrets list --name '${{ inputs.applicationName }}')
        echo "::set-output name=swaSecrets::$secrets"
    - name: EEEEE
      shell: bash
      run: |
        echo ${{ fromJson(steps.get-secrets.outputs.swaSecrets).properties.apiKey }}
    - name: Build and deploy Azure Static Web Apps application 
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ fromJson(steps.get-secrets.outputs.swaSecrets).properties.apiKey }}
        repo_token: ${{ inputs.githubToken }}
        action: 'upload'
        app_location: ${{ inputs.projectWorkspace }}
        output_location: ${{ inputs.outputWorkspace }}
