name: Clean artifacts
description: Clean GitHub Actions artifacts
author: Antoine Milochau
inputs:
  githubToken:
    description: The GitHub token, typically get from secrets.GITHUB_TOKEN
    required: true
  verbosity:
    description: The verbosity of the scripts
    default: minimal
    options:
    - minimal
    - normal
    - detailed
runs:
  using: composite
  steps:
    - name: Deploy Functions application
      uses: azure/powershell@v1
      with:
        inlineScript: ${{ github.action_path }}/clean-artifacts.ps1 `
          -verbosity ${{ inputs.verbosity }}
        azPSVersion: 7.1.0
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
