name: Clean artifacts
description: Clean GitHub Actions artifacts
author: Antoine Milochau
inputs:
  runId:
    description: The id of the GitHub Actions run from which to clean artifacts
    required: true
  verbosity:
    description: The verbosity of the scripts
    default: quiet
    options:
    - quiet
    - minimal
    - normal
    - detailed
    - diagnostic
runs:
  using: composite
  steps:
    - name: Clean artifacts
      shell: pwsh
      run: ${{ github.action_path }}/clean-artifacts.ps1 `
          -runId ${{ inputs.runId }} `
          -verbosity ${{ inputs.verbosity }}
      env:
        GH_TOKEN: ${{ github.token }}