name: Deploy Azure Functions application
description: Deploy Azure Functions application
author: Antoine Milochau
inputs:
  projectsToBuild:
    description: OBSOLETE PARAMETER - The path to the projects to build - can be a .csproj or a .sln file
    required: false
  dotnetVersion:
    description: The .NET version to use
    default: ''
  verbosity:
    description: The verbosity of the dotnet CLI
    default: minimal
  azureCredentials:
    description: Azure credentials, typically get from secrets.AZURE_CREDENTIALS
    required: true
  applicationName:
    description: The application name, as defined on Azure
    required: true
  projectsToPublishPath:
    description: The path of the projects to publish, relative to the checkout path
    required: true
  healthUrl:
    description: The absolute URL of the health endpoint, from the Functions application
    required: false
runs:
  using: composite
  steps:
    - name: Setup .NET Core
      if: ${{ inputs.dotnetVersion != '' }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnetVersion }}
    - name: Login on Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azureCredentials }}
    - name: Deploy Functions application
      shell: pwsh
      run: ${{ github.action_path }}/deploy-functions.ps1 `
        -verbosity ${{ inputs.verbosity }} `
        -applicationName ${{ inputs.applicationName }}
        -healthUrl "${{ inputs.healthUrl }}"
      working-directory: ${{ inputs.projectsToPublishPath }}
