name: Deploy Azure Functions application
description: Deploy Azure Functions application
author: Antoine Milochau
inputs:
  projectsToBuild:
    description: The path to the projects to build - can be a .csproj or a .sln file
    required: true
  verbosity:
    description: The verbosity of the dotnet CLI
    default: minimal
  azureCredentials:
    description: Azure credentials, typically get from secrets.AZURE_CREDENTIALS
    required: true
  applicationName:
    description: The application name, as defined on Azure
    required: true
  projectsToPublishPath:
    description: The path of the projects to publish, relative to the checkout path
    required: true
  healthUrl:
    description: The absolute URL of the health endpoint, from the Functions application
    required: true
runs:
  using: composite
  steps:
    - name: Build projects
      shell: bash
      run: dotnet build ${{ inputs.projectsToBuild }} --configuration Release --output ./output --verbosity ${{ inputs.verbosity }}
    - name: Login on Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azureCredentials }}
    - name: Deploy Azure Functions application
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ inputs.applicationName }}
        package: ./output
    - name: Check health
      shell: pwsh
      run: Invoke-WebRequest ${{ inputs.healthUrl }} -TimeoutSec 120 -MaximumRetryCount 12 -RetryIntervalSec 10
