name: Deploy Azure Functions application
description: Deploy Azure Functions application
author: Antoine Milochau
inputs:
  dotnetVersion:
    description: The .NET version to use
    default: ''
  azureCredentials:
    description: Azure credentials, typically get from secrets.AZURE_CREDENTIALS
    required: true
  applicationName:
    description: The application name, as defined on Azure
    required: true
  projectsToPublishPath:
    description: The path of the projects to publish, relative to the checkout path
    required: true
  healthUrl:
    description: The absolute URL of the health endpoint, from the Functions application
    required: false
  verbosity:
    description: The verbosity of the scripts
    default: minimal
    options:
    - minimal
    - normal
    - detailed
runs:
  using: composite
  steps:
    - name: Setup .NET Core
      if: ${{ inputs.dotnetVersion != '' }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnetVersion }}
    - name: Login on Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azureCredentials }}
        enable-AzPSSession: true
    - name: Deploy Functions application
      uses: azure/powershell@v1
      with:
        inlineScript: ${{ github.action_path }}/deploy-functions.ps1 `
          -projectsToPublishPath ${{ inputs.projectsToPublishPath }} `
          -applicationName ${{ inputs.applicationName }} `
          -healthUrl "${{ inputs.healthUrl }}" `
          -verbosity ${{ inputs.verbosity }}
        azPSVersion: 7.1.0
