name: Deploy Web application
description: Deploy Web application from a Docker image
author: Antoine Milochau
inputs:
  azureCredentials:
    description: Azure credentials, typically get from secrets.AZURE_CREDENTIALS
    required: true
  dockerRegistryHost:
    description: The host of the Docker registry - with a leading slash
    default: 'ghcr.io/'
  dockerImageName:
    description: The name of the Docker image
    required: true
  dockerImageTag:
    description: The tag of the Docker image
    required: true
  resourceGroupName:
    description: The resource group name, as defined on Azure
    required: true
  applicationName:
    description: The application name, as defined on Azure
    required: true
  relativeHealthUrl:
    description: The relative URL of the health endpoint, from the Functions application
    required: false
    default: '/api/health'
runs:
  using: composite
  steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azureCredentials }}
    - name: Deploy Web application
      uses: azure/powershell@v1
      with:
        inlineScript: ${{ github.action_path }}/deploy-web.ps1 `
          -dockerRegistryHost ${{ inputs.dockerRegistryHost }} `
          -dockerImageName ${{ inputs.dockerImageName }} `
          -dockerImageTag ${{ inputs.dockerImageTag }} `
          -resourceGroupName ${{ inputs.resourceGroupName }} `
          -applicationName ${{ inputs.applicationName }} `
          -relativeHealthUrl ${{ inputs.relativeHealthUrl }}
        azPSVersion: 7.1.0
