name: Release npm packages
description: Package, publish and release Node.js libraries as npm packages into npmjs.com
author: Antoine Milochau
inputs:
  projectWorkspace:
    description: The path to the project workspace
    default: '.'
  nodeVersion:
    description: The Node.js version to use
    default: 16.x
  avoidGitHubPrerelease:
    description: Disable GitHub Release creation for unstable version
    required: false
    default: true
  generateReleaseNotes:
    description: Generate automatic release notes
    required: false
    default: false
  githubToken:
    description: The GitHub token, typically get from secrets.GITHUB_TOKEN
    required: true
  mainBranch:
    description: The name of the main branch
    default: 'refs/heads/main'
    required: false
  npmjsComToken:
    description: The npmjs.com token, typically get from a secret; used to publish projects to npmjs.com
    default: ''
    required: false
runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.nodeVersion }}
        cache: 'npm'
        cache-dependency-path: "${{ inputs.projectWorkspace }}/package-lock.json"
    - name: Release npm with script
      shell: pwsh
      run: ${{ github.action_path }}/release-npm.ps1 `
        -mainBranch ${{ inputs.mainBranch }} `
        -currentBranch ${{ github.ref }} `
        -npmjsToken ${{ inputs.npmjsComToken }} `
        -githubToken ${{ inputs.githubToken }} `
        -avoidGithubPrerelease ${{ inputs.avoidGitHubPrerelease }} `
        -generateReleaseNotes ${{ inputs.generateReleaseNotes }}
      working-directory: ${{ inputs.projectWorkspace }}
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}