name: Deploy an API Management backend
description: Deploy an API Management backend
author: Antoine Milochau
inputs:
  azureTemplateVersion:
    description: The version of 'azure-templates' to use
    required: true
  azureCredentials:
    description: Azure credentials, typically get from secrets.AZURE_CREDENTIALS
    required: true
  resourceGroupName:
    description: The name of the resource group where to deploy the infrastructure
    required: true
  templateFilePath:
    description: The path of the infrastructure template to deploy
    required: true
  parametersFilePath:
    description: The path of the parameters files to use during deployment
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2 # For template file
      with:
        repository: amilochau/azure-templates
        ref: ${{ inputs.azureTemplateVersion }}
        path: templates
    - name: Login on Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azureCredentials }}
    - name: Deploy infrastructure to Azure
      uses: Azure/cli@1.0.4
      with:
        inlineScript: |
          az deployment group create \
            --resource-group ${{ inputs.resourceGroupName }} \
            --template-file ${{ inputs.templateFilePath }} \
            --parameters ${{ inputs.parametersFilePath }}
