name: Deploy Azure infrastructure
description: Deploy Azure infrastructure
author: Antoine Milochau
inputs:
  azureTemplateVersion:
    description: The version of 'azure-templates' to use
    required: true
  azureCredentials:
    description: Azure credentials, typically get from secrets.AZURE_CREDENTIALS
    required: true
  scopeType:
    description: The deployment scope type
    type: choice
    options:
    - resourceGroup
    - subscription
    - managementGroup
    default: resourceGroup
  scopeLocation:
    description: The deployment scope location (Azure region)
    required: true
  resourceGroupName:
    description: The name of the resource group where to deploy the infrastructure
    required: false
  subscriptionId:
    description: The ID of the Azure subscription
    required: false
  managementGroupId:
    description: The ID of the Azure management group
    required: false
  templateType:
    description: The type of Azure templates to use
    required: true
    options:
    - configuration
    - functions
    - functions/api-registration
    - functions/local-dependencies
    - gateway
    - management-group
    - monitoring
    - static-web-apps
  parametersFilePath:
    description: The path of the parameters files to use during deployment
    required: true
  deploymentName:
    description: The name of the deployment into Azure
    required: false
    default: 'Deployment-GitHub'
outputs:
  resourceId:
    description: "The ID of the main deployed resource"
    value: ${{ steps.deploy.outputs.resourceId }}
  resourceName:
    description: "The name of the main deployed resource"
    value: ${{ steps.deploy.outputs.resourceName }}
  verbosity:
    description: The verbosity of the scripts
    default: minimal
    options:
    - minimal
    - normal
    - detailed
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2 # For template file
      with:
        repository: amilochau/azure-templates
        ref: ${{ inputs.azureTemplateVersion }}
        path: templates
        fetch-depth: 0
    - name: Login on Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azureCredentials }}
        enable-AzPSSession: true
    - name: Deploy infrastructure on Azure with script
      id: deploy
      uses: azure/powershell@v1
      with:
        inlineScript: ${{ github.action_path }}/deploy-infrastructure.ps1 `
          -scopeType ${{ inputs.scopeType }} `
          -scopeLocation ${{ inputs.scopeLocation }} `
          -resourceGroupName "${{ inputs.resourceGroupName }}" `
          -subscriptionId "${{ inputs.subscriptionId }}" `
          -managementGroupId "${{ inputs.managementGroupId }}" `
          -templateType ${{ inputs.templateType }} `
          -parametersFilePath ${{ inputs.parametersFilePath }} `
          -deploymentName ${{ inputs.deploymentName }} `
          -templatesDirectory ./templates
        azPSVersion: 7.1.0
