name: Deploy Azure infrastructure
description: Deploy Azure infrastructure
author: Antoine Milochau
inputs:
  azureTemplateVersion:
    description: The version of 'azure-templates' to use
    required: true
  azureCredentials:
    description: Azure credentials, typically get from secrets.AZURE_CREDENTIALS
    required: true
  scope:
    description: Deployment scope
    type: choice
    options:
    - resourceGroup
    - subscription
    - managementGroup
    default: resourceGroup
  resourceGroupName:
    description: The name of the resource group where to deploy the infrastructure
    required: false
  resourceGroupLocation:
    description: The location of the resource group where to deploy the infrastructure
    required: false
  subscriptionId:
    description: The ID of the Azure subscription
    required: false
  subscriptionRegion:
    description: The region of the Azure subscription
    required: false
  managementGroupId:
    description: The ID of the Azure management group
    required: false
  managementGroupRegion:
    description: The region of the Azure management group
    required: false
  templateFilePath:
    description: OBSOLETE (use 'templateType') The path of the infrastructure template to deploy
    required: false
  templateType:
    description: The type of Azure templates to use
    required: false
    options:
    - configuration
    - functions
    - functions/api-registration
    - functions/local-dependencies
    - gateway
    - management-group
    - monitoring
    - static-web-apps
  parametersFilePath:
    description: The path of the parameters files to use during deployment
    required: true
  deploymentName:
    description: The name of the deployment into Azure
    required: false
    default: 'Deployment-GitHub'
outputs:
  resourceId:
    description: "The ID of the main deployed resource"
    value: ${{ steps.deploy.outputs.resourceId }}
  resourceName:
    description: "The name of the main deployed resource"
    value: ${{ steps.deploy.outputs.resourceName }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2 # For template file
      with:
        repository: amilochau/azure-templates
        ref: ${{ inputs.azureTemplateVersion }}
        path: templates
        fetch-depth: 0
    - name: Login on Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azureCredentials }}
    - name: Deploy infrastructure on Azure with script
      id: deploy
      shell: pwsh
      run: ${{ github.action_path }}/deploy-infrastructure.ps1 `
        -scope ${{ inputs.scope }} `
        -resourceGroupName "${{ inputs.resourceGroupName }}" `
        -resourceGroupLocation "${{ inputs.resourceGroupLocation }}" `
        -subscriptionId "${{ inputs.subscriptionId }}" `
        -subscriptionLocation "${{ inputs.subscriptionRegion }}" `
        -managementGroupId "${{ inputs.managementGroupId }}" `
        -managementGroupLocation "${{ inputs.managementGroupRegion }}" `
        -templateFilePath "${{ inputs.templateFilePath }}" `
        -templateType "${{ inputs.templateType }}"
        -parametersFilePath ${{ inputs.parametersFilePath }} `
        -deploymentName ${{ inputs.deploymentName }}
        -templatesDirectory ./templates
