name: Release
run-name: Release - ${{ github.ref }}

on:
  workflow_dispatch:
    inputs:
      versionMajor:
        description: Major version - must be changed when you make incompatible API changes
        required: true
      versionMinor:
        description: Minor version - must be changed when you add functionality in a backward compatible manner
        required: true
      versionPatch:
        description: Patch version - must be changed when you make backwards compatible bug fixes
        required: true
      versionUnstableSuffix:
        description: Unstable suffix version - must be added when you want to create a pre-release
        required: false
        default: ''

concurrency: release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    environment: RELEASE
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up a GitHub Release
        uses: amilochau/github-actions/release/basic@main
        with:
          versionMajor: ${{ github.event.inputs.versionMajor }}
          versionMinor: ${{ github.event.inputs.versionMinor }}
          versionPatch: ${{ github.event.inputs.versionPatch }}
          versionUnstableSuffix: ${{ github.event.inputs.versionUnstableSuffix }}
